=== tdonkor/PAY_UK_LANE3000/Driver/Pay_UK_LANE3000/c3config_receipt.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.ingenico.com/C3ConfigXMLSchema" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.ingenico.com/C3ConfigXMLSchema">
	<xs:element name="field">
		<xs:complexType>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="print" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="YES"/>
						<xs:enumeration value="NO"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="position" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="RIGHT"/>
						<xs:enumeration value="CENTER"/>
						<xs:enumeration value="LEFT"/>
						<xs:enumeration value="JUSTIFIED"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="wordwrap" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="NO"/>
						<xs:enumeration value="YES"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="emptyline" use="optional" default="0">
				<xs:simpleType>
					<xs:restriction base="xs:int">
						<xs:minInclusive value="0"/>
						<xs:maxInclusive value="9"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="mode" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="config">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="application" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="receipt">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="field" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="CLIENT"/>
						<xs:enumeration value="DETAILS"/>
						<xs:enumeration value="MERCHANT"/>
						<xs:enumeration value="DUPLICATE"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="application">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="receipt" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="AGC"/>
						<xs:enumeration value="CCP"/>
						<xs:enumeration value="CLS"/>
						<xs:enumeration value="EHL"/>
						<xs:enumeration value="DCI"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== tdonkor/PAY_UK_LANE3000/Driver/Pay_UK_LANE3000/c3config_receipt.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.ingenico.com/C3ConfigXMLSchema" xsi:schemaLocation="http://www.ingenico.com/C3ConfigXMLSchema c3config_receipt.xsd">
	<application name="CLS">
		<receipt name="CLIENT">
			<field name="HEADER" print="YES" position="CENTER" emptyline="1"/>
			<field name="MERCHANT_NAME_LINE1" print="YES" position="LEFT"/>
			<field name="MERCHANT_NAME_LINE2" print="YES" position="LEFT"/>
			<field name="MERCHANT_NAME_LINE3" print="YES" position="LEFT"/>
			<field name="AID" print="YES" position="LEFT"/>
			<field name="CARDSCHEME" print="YES" position="LEFT"/>
			<field name="PAN" print="YES" position="LEFT"/>
			<field name="CARD_SEQUENCE_NUMBER" print="YES" position="LEFT"/>
			<field name="SWIPED_ISSUE_NUMBER" print="YES" position="LEFT"/>
			<field name="ENTRY_MODE" print="YES" position="LEFT"/>
			<field name="USER_DATA_1" print="YES" position="LEFT"/>
			<field name="USER_DATA_2" print="YES" position="LEFT"/>
			<field name="TRANSACTION_TYPE" print="YES" position="CENTER"/>
			<field name="AMOUNT" print="YES" position="CENTER" wordwrap="YES"/>
			<field name="CASH_AMOUNT" print="YES" position="CENTER" wordwrap="YES"/>
			<field name="TOTAL_AMOUNT" print="YES" position="CENTER" wordwrap="YES"/>
			<field name="AVAILABLE_AMOUNT" print="YES" position="CENTER"  wordwrap="YES"/>
			<field name="ACCOUNT_VERIFICATION_RESULT" print="YES" position="LEFT"/>
			<field name="CARDHOLDER_VERIFICATION_METHOD" print="YES" position="LEFT"/>
			<field name="AUTHORISATION_CODE" print="YES" position="LEFT"/>
			<field name="TRANSACTION_NUMBER" print="YES" position="LEFT"/>
			<field name="MID" print="YES" position="LEFT"/>
			<field name="TID" print="YES" position="LEFT"/>
			<field name="CRYPTOGRAM" print="YES" position="LEFT"/>
			<field name="DATE_TIME" print="YES" position="LEFT" emptyline="1"/>
			<field name="DCC_AMOUNT" print="YES" position="CENTER"  wordwrap="YES"/>
			<field name="DCC_EXCHANGE_RATE" print="YES" position="CENTER"  wordwrap="YES"/>
			<field name="DCC_COMMISSION" print="YES" position="CENTER"  wordwrap="YES"/>
			<field name="DCC_MARKUP" print="YES" position="CENTER"  wordwrap="YES"/>
			<field name="DCC_DISCLAIMER" print="YES" position="LEFT"/>
			<field name="DCC_EXCHANGE_SOURCE" print="YES" position="LEFT"/>
			<field name="RECEIPT_TYPE" print="YES" position="CENTER"/>
			<field name="RETAIN_MESSAGE" print="YES" position="LEFT"/>
			<field name="RETAILER_LINE1" print="YES" position="LEFT"/>
			<field name="RETAILER_LINE2" print="YES" position="LEFT"/>
			<field name="ABORT_MESSAGE" print="YES" position="LEFT" emptyline="1"/>
			<field name="TEST_CARD_MESSAGE" print="YES" position="LEFT"/>
		</receipt>
		<receipt name="MERCHANT">
			<field name="HEADER" print="YES" position="CENTER" emptyline="1"/>
			<field name="MERCHANT_NAME_LINE1" print="YES" position="LEFT"/>
			<field name="MERCHANT_NAME_LINE2" print="YES" position="LEFT"/>
			<field name="MERCHANT_NAME_LINE3" print="YES" position="LEFT"/>
			<field name="AID" print="YES" position="LEFT"/>
			<field name="CARDSCHEME" print="YES" position="LEFT"/>
			<field name="PAN" print="YES" position="LEFT"/>
			<field name="START_DATE" print="YES" position="LEFT"/>
			<field name="EXPIRY_DATE" print="YES" position="LEFT"/>
			<field name="CARD_SEQUENCE_NUMBER" print="YES" position="LEFT"/>
			<field name="SWIPED_ISSUE_NUMBER" print="YES" position="LEFT"/>
			<field name="ENTRY_MODE" print="YES" position="LEFT"/>
			<field name="USER_DATA_1" print="YES" position="LEFT"/>
			<field name="USER_DATA_2" print="YES" position="LEFT"/>
			<field name="TRANSACTION_TYPE" print="YES" position="CENTER"/>
			<field name="AMOUNT" print="YES" position="CENTER" wordwrap="YES"/>
			<field name="CASH_AMOUNT" print="YES" position="CENTER"  wordwrap="YES"/>
			<field name="TOTAL_AMOUNT" print="YES" position="CENTER"  wordwrap="YES"/>
			<field name="AVAILABLE_AMOUNT" print="YES" position="CENTER"  wordwrap="YES"/>
			<field name="ACCOUNT_VERIFICATION_RESULT" print="YES" position="LEFT"/>
			<field name="MERCHANT_SIGNATURE_MESSAGE" print="YES" position="LEFT" emptyline="3"/>
			<field name="TRANSACTION_MESSAGE_1" print="YES" position="CENTER"/>
			<field name="TRANSACTION_MESSAGE_2" print="YES" position="CENTER"/>
			<field name="CARDHOLDER_VERIFICATION_METHOD" print="YES" position="LEFT"/>
			<field name="AUTHORISATION_CODE" print="YES" position="LEFT"/>
			<field name="TRANSACTION_IDENTIFIER" print="YES" position="LEFT"/>
			<field name="TRANSACTION_NUMBER" print="YES" position="LEFT"/>
			<field name="FILE_NUMBER" print="YES" position="LEFT"/>
			<field name="MID" print="YES" position="LEFT"/>
			<field name="TID" print="YES" position="LEFT"/>
			<field name="CRYPTOGRAM" print="YES" position="LEFT"/>
			<field name="DATE_TIME" print="YES" position="LEFT" emptyline="1"/>
			<field name="DCC_AMOUNT" print="YES" position="CENTER"  wordwrap="YES"/>
			<field name="DCC_EXCHANGE_RATE" print="YES" position="CENTER"  wordwrap="YES"/>
			<field name="DCC_COMMISSION" print="YES" position="CENTER"  wordwrap="YES"/>
			<field name="DCC_MARKUP" print="YES" position="CENTER"  wordwrap="YES"/>
			<field name="DCC_DISCLAIMER" print="YES" position="LEFT"/>
			<field name="DCC_EXCHANGE_SOURCE" print="YES" position="LEFT"/>
			<field name="RECEIPT_TYPE" print="YES" position="CENTER"/>
			<field name="RETAILER_LINE1" print="YES" position="LEFT"/>
			<field name="RETAILER_LINE2" print="YES" position="LEFT"/>
			<field name="ABORT_MESSAGE" print="YES" position="LEFT" emptyline="1"/>
			<field name="TEST_CARD_MESSAGE" print="YES" position="LEFT"/>
			<field name="EMV_DEBUG" print="YES" position="LEFT" mode="FULL"/>
		</receipt>
		<receipt name="DETAILS">
			<field name="HEADER" print="YES" position="CENTER"/>
			<field name="MERCHANT_NAME_LINE1" print="YES" position="LEFT"/>
			<field name="MERCHANT_NAME_LINE2" print="YES" position="LEFT"/>
			<field name="MERCHANT_NAME_LINE3" print="YES" position="LEFT"/>
			<field name="USER_DATA_1" print="YES" position="LEFT"/>
			<field name="USER_DATA_2" print="YES" position="LEFT"/>
			<field name="PAN" print="YES" position="LEFT"/>
			<field name="CARD_SEQUENCE_NUMBER" print="YES" position="LEFT"/>
			<field name="EXPIRY_DATE_STATUS" print="YES" position="LEFT"/>
			<field name="AMOUNT" print="YES" position="LEFT"/>
			<field name="MID" print="YES" position="LEFT"/>
			<field name="TID" print="YES" position="LEFT"/>
		</receipt>
	</application>
	<application name="EHL">
		<receipt name="CLIENT">
			<field name="RETAILER_HEADER_LINE1" print="YES" position="LEFT"/>
			<field name="RETAILER_HEADER_LINE2" print="YES" position="LEFT"/>
			<field name="MERCHANT_NAME_LINE1" print="YES" position="LEFT"/>
			<field name="MERCHANT_NAME_LINE2" print="YES" position="LEFT"/>
			<field name="MERCHANT_NAME_LINE3" print="YES" position="LEFT"/>
			<field name="CASHIER_NUMBER" print="YES" position="LEFT"/>
			<field name="DATE_TIME" print="YES" position="LEFT" emptyline="1"/>
			<field name="HOST_RECEIPT" print="YES" position="LEFT" emptyline="2"/>
			<field name="RETAIL_TRANSACTION_REFERENCE" print="YES" position="LEFT" emptyline="2"/>
			<field name="RETAILER_LINE1" print="YES" position="LEFT"/>
			<field name="RETAILER_LINE2" print="YES" position="LEFT"/>
		</receipt>
		<receipt name="DUPLICATE">
			<field name="RETAILER_HEADER_LINE1" print="YES" position="LEFT"/>
			<field name="RETAILER_HEADER_LINE2" print="YES" position="LEFT"/>
			<field name="MERCHANT_NAME_LINE1" print="YES" position="LEFT"/>
			<field name="MERCHANT_NAME_LINE2" print="YES" position="LEFT"/>
			<field name="MERCHANT_NAME_LINE3" print="YES" position="LEFT"/>
			<field name="CASHIER_NUMBER" print="YES" position="LEFT"/>
			<field name="DATE_TIME" print="YES" position="LEFT" emptyline="1"/>
			<field name="TRANSACTION_TYPE" print="YES" position="CENTER"/>
			<field name="RETAIL_TRANSACTION_REFERENCE" print="YES" position="LEFT" emptyline="1"/>
			<field name="ACQUIRER_TRANSACTION_ID" print="YES" position="LEFT"/>
			<field name="AMOUNT" print="YES" position="LEFT" emptyline="1"/>
			<field name="TRANSACTION_TYPE" print="YES" position="CENTER" emptyline="3"/>
			<field name="RETAILER_LINE1" print="YES" position="LEFT"/>
			<field name="RETAILER_LINE2" print="YES" position="LEFT"/>
		</receipt>
	</application>
	<application name="AGC">
		<receipt name="CLIENT">
			<field name="HEADER" print="YES" position="CENTER" emptyline="1"/>
			<field name="MERCHANT_NAME_LINE1" print="YES" position="LEFT"/>
			<field name="MERCHANT_NAME_LINE2" print="YES" position="LEFT"/>
			<field name="MERCHANT_NAME_LINE3" print="YES" position="LEFT"/>
			<field name="CARDSCHEME" print="YES" position="LEFT"/>
			<field name="PAN" print="YES" position="LEFT"/>
			<field name="ENTRY_MODE" print="YES" position="LEFT"/>
			<field name="USER_DATA_1" print="YES" position="LEFT"/>
			<field name="USER_DATA_2" print="YES" position="LEFT"/>
			<field name="TRANSACTION_TYPE" print="YES" position="CENTER"/>
			<field name="AMOUNT" print="YES" position="CENTER" wordwrap="YES"/>
			<field name="BALANCE" print="YES" position="LEFT" wordwrap="NO"/>
			<field name="OPENING_BALANCE" print="YES" position="LEFT" wordwrap="NO"/>
			<field name="CLOSING_BALANCE" print="YES" position="LEFT" wordwrap="NO"/>
			<field name="ACCOUNT_VERIFICATION_RESULT" print="YES" position="LEFT"/>
			<field name="CARDHOLDER_VERIFICATION_METHOD" print="YES" position="LEFT"/>
			<field name="AUTHORISATION_CODE" print="YES" position="LEFT"/>
			<field name="TRANSACTION_NUMBER" print="YES" position="LEFT"/>
			<field name="MID" print="YES" position="LEFT"/>
			<field name="TID" print="YES" position="LEFT"/>
			<field name="DATE_TIME" print="YES" position="LEFT" emptyline="1"/>
			<field name="RECEIPT_TYPE" print="YES" position="CENTER"/>
			<field name="RETAIN_MESSAGE" print="YES" position="LEFT" emptyline="1"/>
